// Generated by CoffeeScript 1.3.3
var crypto, request, _;

crypto = require("crypto");

request = require("request");

_ = require("underscore");

module.exports = function(input, callback) {
  var options;
  options = {
    uri: '//api.coolsms.co.kr/sendmsg',
    ssl: false,
    user: 'user',
    password: 'password',
    enc: 'md5',
    to: '',
    from: '',
    text: ''
  };
  options = _.extend(options, input);
  options.password = crypto.createHash(options.enc).update(options.password).digest("hex");
  return request.post({
    uri: (options.ssl ? "https:" : "http:") + options.uri,
    form: {
      user: options.user,
      password: options.password,
      enc: options.enc,
      to: options.to,
      from: options.from,
      text: options.text
    }
  }, function(err, res, body) {
    var line, lines, messages, part, _i, _len;
    messages = {};
    lines = body.split('\n');
    for (_i = 0, _len = lines.length; _i < _len; _i++) {
      line = lines[_i];
      part = line.split('=');
      if (part[0].trim().length > 0) {
        messages[part[0]] = part[1];
      }
    }
    return callback(err, messages);
  });
};
