// Generated by CoffeeScript 1.3.3
(function() {
  var crypto, request, _;

  crypto = require("crypto");

  request = require("request");

  _ = require("underscore");

  module.exports = function(input, callback) {
    var options;
    options = {
      uri: '//api.coolsms.co.kr/sendmsg',
      method: 'post',
      ssl: false,
      user: 'user',
      password: 'password',
      enc: 'md5',
      to: '',
      from: '',
      text: ''
    };
    options = _.extend(options, input);
    options.password = crypto.createHash(options.enc).update(options.password).digest("hex");
    return request({
      method: options.method,
      uri: (ssl ? "https" : "http") + options.uri,
      json: {
        user: options.user,
        password: options.password,
        enc: options.enc,
        to: options.to,
        from: options.from,
        text: options.text
      }
    }, function(err, res, body) {
      return callback(err, res, body);
    });
  };

}).call(this);
